### ISSUE TITLE
Improve the frontend deployment to support the increasing traffic

### ISSUE THREAD

**Issue by rach-id** [celestiaorg/big-dipper-2.0-cosmos#11]
## Issue
Currently, the explorer is being accessed by lot of users, and it is failing to serve them all fast. 
That's because we are only doing a simple prod deployment and using nginx as a reverse proxy.

## Proposition
Deploy multiple instances (I will start with 3) of the explorer frontend using `docker-compose` and eventually using `k8s` for testnet if we expect a lot of traffic (but not now, it will be way more expensive and would require more work IMO). Then, using nginx to load balance between them.
This would help serve more requests and make the user experience better.
Also, we would need to resize the machine and go for higher number of CPUs. Currently, it has 4 CPUs. Thus, I guess I will go for 8 CPUs next.

## Add-on
We should also resize the current `devnet-2` node used for the explorer as it is failing to support the huge validators number (not sure if it related, but the machine is running always at ~60% CPU load, and it fails to catch up to the network most times) and also serve more requests from the explorer backend, as we will increase the number of requests and workers for the backend also.

**Comment by rach-id** [comment]
We can go for these changes as soon as the new `PayForMsg` support is merged and is deployable. https://github.com/celestiaorg/big-dipper-2.0-cosmos/pull/10

**Comment by rach-id** [comment]
@liamsi @evan-forbes What do you think of this ?

**Comment by rach-id** [comment]
For the staking UI and Keplr, so far, we don't seem to have much load on it. However, once we start having more users, we would need to think of a scaling solution for it also.

**Comment by evan-forbes** [comment]
This seems reasonable and inevitable. Not sure exactly where the bottlenecks are, but I think this should get us through testnet and hopefully incentivized testnet if we don't have other block explorers by then.

**Comment by rach-id** [comment]
It is currently in the frontend. It is not as fast as the other components, and it's normal because I am only deploying it similar to what we do in dev environment. Therefore, I will serve it using `pm2-runtime` as it is more adequate in a production environment and have 3 replicas running. So it would hopefully be significantly faster.

**Comment by liamsi** [comment]
I think we should prepare for this but I don't think it is very urgent right now. Maybe for the next testnet or even the incetivized one. BTW, would also loop in @jbowen93 as he had some ideas around load balancers etc.

**Comment by rach-id** [comment]
Currently, the explorer is lagging behind and requests take time. We can experience with it to know which configuration is right to handle the load and have it ready for upcoming networks. 
For using `docker-compose` to manage replicas and stuff, it is straightforward and wouldn't require much work. I can do it while deploying the new `PayForMsg` changes once https://github.com/celestiaorg/big-dipper-2.0-cosmos/pull/10 is merged.
And if multiple instances of the frontend and a higher number of workers on the backend solved the issue. Then, we can think of advanced k8s autoscaling and stuff. 
What do you think ?

**Comment by rach-id** [comment]
Current deployment config is in this branch: [chains/celestia-deployment](chains/celestia-deployment)

**Comment by rach-id** [comment]
Deployed. 
There is a slight change, I didn't use the `replicas` property of `docker-compose` for `graphql` engine as it meant double proxying `ws` traffic which resulted in facing `CORS` exceptions and stuff which is not worth wasting time on at the moment.
Thus, the load balancing is done using `upstream` in `nginx` with multiple containers created manually.
For `big-dipper` load, it is done using `replicas` as it is ordinary `HTTP` traffic.
Closing.
