### ISSUE TITLE
Rename PayForMessage to PayForData

### ISSUE THREAD

**Issue by rach-id** [celestiaorg/big-dipper-2.0-cosmos#17]
As of https://github.com/celestiaorg/big-dipper-2.0-cosmos/commit/de82d67cc7a0fdb66ba1e63e7ab8be7903372043, we had support for `PayForMessage`. However, in https://github.com/celestiaorg/celestia-app/pull/371, that was renamed to `PayForData`. The explorer also needs to support this change.

**Comment by lzrscg** [comment]
done
