### ISSUE TITLE
Fix testnet/mainnet config to reflect the correct `celes`/`uceles` units

### ISSUE THREAD

**Issue by rach-id** [celestiaorg/big-dipper-2.0-cosmos#5]
Currently, our deployment of big dipper uses `celes` and `uceles` interchangeably. This is due to a confusion in the `devnet-2` genesis file generation, where the units are not properly defined.
In upcoming networks, we will have a correct genesis and thus the configuration under `src/configs` should be updated to reflect that change.

**Comment by lzrscg** [comment]
done

**Comment by rach-id** [comment]
Can you please  open a PR to this repo containing this change ?
